baseurl = "https://statkim.github.io/blogdown_test/"
title = "statKim Blog"
languageCode = "ko-KR"

theme = "hugo-hello-programmer-theme"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

paginate = 2

disqusShortname = "statKim"
googleAnalytics = "UA-XXXXXXXX-X"

publishDir = "docs"


[author]
    name = "your-name"
    email = "your-email"
