baseurl = "https://statkim.github.io/blogdown_test"
title = "statKim Blog"
languageCode = "ko-KR"

theme = "hugo-hello-programmer-theme"

paginate = 2

disqusShortname = "statKim"
googleAnalytics = "UA-XXXXXXXX-X"

[author]
    name = "statKim (HYUNSUNG, KIM)"
    email = "hyunsung1021@gmail.com"
